#!/bin/bash
# Deploy to Railway
# This script sets up your backend on Railway

echo "🚀 Levi Oils - Railway Backend Deployment"
echo "=========================================="
echo ""
echo "STEP 1: Create Railway Account"
echo "1. Go to https://railway.app"
echo "2. Click 'Start Project'"
echo "3. Sign in with GitHub"
echo ""
echo "STEP 2: Connect Your Repository"
echo "1. In Railway dashboard, click 'New Project'"
echo "2. Select 'Deploy from GitHub'"
echo "3. Find and select: oil-website-2"
echo ""
echo "STEP 3: Configure Deployment"
echo "1. Click 'Configure'/'Next'"
echo "2. Root Directory: server"
echo "3. Deploy!"
echo ""
echo "STEP 4: Get Your Railway URL"
echo "1. Wait for deployment to complete (green checkmark)"
echo "2. Click your project"
echo "3. Find 'Service Domain' - this is your backend URL"
echo "   Format: https://something.railway.app"
echo ""
echo "STEP 5: Update Frontend"
echo "1. Edit config.js"
echo "2. Change: const CONFIG = { apiUrl: 'https://YOUR-RAILWAY-URL' };"
echo "3. Replace YOUR-RAILWAY-URL with your Railway domain"
echo "4. Commit and push"
echo ""
echo "STEP 6: Test"
echo "1. Go to https://levioils.vercel.app/order-history.html"
echo "2. Enter email and click 'Find Orders'"
echo "3. Should show orders (no more 404!) ✓"
echo ""
echo "=========================================="
